<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_bot_laser">

    <!-- Laser dimensions -->
    <xacro:property name="laser_diam" value="0.1" />
    <xacro:property name="laser_rad" value="${laser_diam/2.0}" />
    <xacro:property name="laser_height" value="0.05" />
    <xacro:property name="half_laser_height" value="${laser_height/2.0}" />

    <xacro:property name="laser_mount_height" value="0.025" />
    <xacro:property name="half_laser_mount_height" value="${laser_mount_height/2.0}" />

    <xacro:property name="laserOz" value="${half_laser_mount_height + half_laser_height}" />
    <xacro:property name="laser_mountOz" value="${half_body_height + half_laser_mount_height}" />

    <!-- Laser mount link -->
    <link name="laser_mount_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_mount_height}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_mount_height}" />
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.5"/>
    </link>

    <joint name="laser_mount_joint" type="fixed">
        <parent link="body_link" />
        <child link="laser_mount_link" />
        <origin xyz="0 0 ${laser_mountOz}" rpy="0 0 ${M_PI}" />
    </joint>

    <!-- Laser link -->
    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_height}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_rad}" length="${laser_height}" />
            </geometry>
        </collision>
        <xacro:default_inertial mass="5"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="laser_mount_link" />
        <child link="laser_link" />
        <origin xyz="0 0 ${laserOz}" rpy="0 0 0" />
    </joint>

    <!-- Laser Gazebo plugin -->
    <gazebo reference="laser_link">
        <sensor type="ray" name="laser">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>35</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle> <!-- -2.96706 -->
                        <max_angle>3.14159</max_angle> <!-- 2.96706 -->
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise parameters based on published spec for Hokuyo laser
                        achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                        stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                        reading. -->
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/mobile_bot/laser/scan</topicName>
                <frameName>laser_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>