<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_bot">

    <!-- Xacro properties -->

    <!-- Body dimensions -->
    <xacro:property name="body_len" value="0.325"/>
    <xacro:property name="body_width" value="0.340"/>
    <xacro:property name="body_height" value="0.1345"/>
    <xacro:property name="clearance" value="0.025"/>

    <xacro:property name="half_body_len" value="${body_len/2.0}"/>
    <xacro:property name="half_body_height" value="${body_height/2.0}"/>
    <xacro:property name="bodyOz" value="${half_body_height + clearance}"/>

    <!-- Wheel dimensions -->
    <xacro:property name="wheel_diam" value="0.1016"/>
    <xacro:property name="wheel_rad" value="${wheel_diam/2.0}"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_sep" value="${body_width - wheel_width}"/>
    <xacro:property name="wheelOx" value="${half_body_len - wheel_rad}"/>
    <xacro:property name="wheelOy" value="${wheel_sep/2.0}"/>
    <xacro:property name="wheelOz" value="${wheel_rad - bodyOz}"/>

    <!-- Castor dimensions -->
    <xacro:property name="castor_diam" value="0.050"/>
    <xacro:property name="castor_rad" value="${castor_diam/2.0}"/>
    <xacro:property name="wheel_to_castor" value="0.2415"/>
    <xacro:property name="castorOx" value="${wheelOx - wheel_to_castor}"/>
    <xacro:property name="castorOz" value="${castor_rad - bodyOz}"/>

    <xacro:property name="M_PI" value="3.14159265359"/>

    <!-- Material Definitions -->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <!-- Default Inertial macro -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0"/>
        </inertial>
    </xacro:macro>

    <!-- Robot base link -->
    <link name="base_link"/>

    <!-- Robot Body Link -->
    <link name="body_link">
        <visual>
            <geometry>
                <box size="${body_len} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_len} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="20"/>
    </link>

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
    </joint>

    <!-- Wheel macro -->
    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
                </geometry>           
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <axis xyz="0 0 1"/>
            <parent link="body_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${wheelOx} ${reflect*wheelOy} ${wheelOz}" rpy="${-M_PI/2.0} 0 0"/>
            <limit effort="100" velocity="15"/>
            <joint_properties damping="0.0" friction="0.0"/>
        </joint>

        <gazebo reference="{prefix}_wheel_link">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0"/>
            <kd value="1.0"/>
            <material>Gazebo/Grey</material>
        </gazebo>

        <transmission name="${prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>

    <!-- Wheels -->
    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>

    <!-- Front castor -->
    <link name="castor_link">
        <visual>
            <geometry>
                <sphere radius="${castor_rad}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${castor_rad}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.5"/>
    </link>

    <joint name="castor_joint" type="fixed">
        <parent link="body_link"/>
        <child link="castor_link"/>
        <origin xyz="${castorOx} 0 ${castorOz}" rpy="0 0 0"/>
    </joint>

    <!-- Tell Gazebo it has 0 friction -->
    <gazebo reference="castor_link">
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
    </gazebo>

    <!-- Camera and Laser -->
    <xacro:include filename="$(find mobile_bot)/urdf/mobile_bot/mobile_bot_camera.urdf.xacro" />
    <xacro:include filename="$(find mobile_bot)/urdf/mobile_bot/mobile_bot_laser.urdf.xacro" />
    <xacro:include filename="$(find mobile_bot)/urdf/mobile_bot/mobile_bot_imu.urdf.xacro" />

    <!-- Gazebo plugin for ROS Control -->
    <gazebo> 
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>20.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>ground_truth/state</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>  

        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

</robot>