<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobot_xacro_defs">

    <!-- Main Body Dimensions -->
    <xacro:property name="bodylen" value="0.4"/>
    <xacro:property name="bodywidth" value="0.5"/>
    <xacro:property name="bodyheight" value="0.25"/>
    <xacro:property name="bodyclearance" value="0.25"/>
    <xacro:property name="half_bodylen" value="${bodylen/2.0}"/>
    <xacro:property name="half_bodyheight" value="${bodyheight/2.0}"/>

    <!-- Body location relative to base link frame -->
    <xacro:property name="bodyOX" value="0"/>
    <xacro:property name="bodyOY" value="0"/>
    <xacro:property name="bodyOZ" value="${bodyclearance}"/>

    <!-- Wheel Dimensions -->
    <xacro:property name="wheeldiam" value="${bodyclearance}"/>
    <xacro:property name="wheelrad" value="${wheeldiam/2.0}"/>
    <xacro:property name="wheelwidth" value="0.05"/>
    <xacro:property name="wheeldist" value="0.45"/>

    <xacro:property name="M_PI" value="3.14159265359"/>

    <!-- Default Inertia Matrix -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01"/>
        </inertial>
    </xacro:macro>
</robot>