# Configuration file for mobile bot controllers
mobile_bot:
  # Differential Drive controller parameters
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50

    left_wheel: ['left_wheel_joint']
    right_wheel: ['right_wheel_joint']

    # Infer wheel separation and wheel radius from description files

    # Odometry covariances for the encoder output of the robot.
    # Tune to the robot's sample odometry data
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5] #[0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

    # Top level frame (link) of the robot
    base_frame_id: base_link

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.6   # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.6   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0   # rad/s^2

  # The joint state controller handles publishing transforms for any moving joints  
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50